name: Caching Primes

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build executable
        run: |
          echo "echo 'hello world'" >> executable.sh
          chmod +x executable.sh
      - name: Cache executable
        id: cache-executable
        uses: actions/cache@v4
        with:
          path: executable.sh
          key: executable
